version: "3.9"
services:
  db-mongo-1:
    image: mongo:5.0.2
    restart: always
    volumes:
      - ./db-mongo-1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Rahasia88oke
  
  mongo-express-admin:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Rahasia88oke
      ME_CONFIG_MONGODB_URL: mongodb://root:Rahasia88oke@db-mongo-1:27017/

  mongo-exporter-1:
    image: bitnami/mongodb-exporter:0.20.7
    restart: always
    environment:
      - "MONGODB_URI=mongodb://root:Rahasia88oke@db-mongo-1:27017/"
    links:
      - db-mongo-1
    depends_on:
      - db-mongo-1
  
networks:
  default:
    external: true
    name: prometheus-metrics