version: "3.9"
services:
  db-mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./sql_databases/db_1:/var/lib/mysql
      - ./sql_scripts/db_1:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Rahasia88oke#
 
  mysqld-exporter:
    image: prom/mysqld-exporter:v0.13.0
    command:
      - --collect.info_schema.tablestats
      - --collect.info_schema.query_response_time
    environment:
      - DATA_SOURCE_NAME=root:Rahasia88oke#@(db-mysql:3306)/
    links:
      - db-mysql
    depends_on:
      - db-mysql
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined      

  db-mysql-2:
    image: mysql:8.0
    restart: always
    volumes:
      - ./sql_databases/db_2:/var/lib/mysql
      - ./sql_scripts/db_2:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Rahasia88oke#

  mysqld-exporter2:
    image: prom/mysqld-exporter:v0.13.0
    command:
      - --collect.info_schema.tablestats
      - --collect.info_schema.query_response_time
    environment:
      - DATA_SOURCE_NAME=root:Rahasia88oke#@(db-mysql-2:3306)/
    links:
      - db-mysql-2
    depends_on:
      - db-mysql-2 

networks:
  default:
    external: true
    name: prometheus-metrics   
