version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.29.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  node:
    image: prom/node-exporter:v1.2.2
    ports:
      - 9100:9100
    volumes:
      - "/:/rootfs"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8082:8080"    
      
networks:
  default:
    external: true
    name: prometheus-metrics 