version: "3.9"
services:
  db-postgres-1:
    image: postgres:13.4
    restart: always
    volumes:
      - ./db-postgres-1:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rahasia88oke
      PGDATA: /var/lib/postgresql/data/db_01

  postgres-exporter-1:
    image: bitnami/postgres-exporter:0.10.0
    restart: always
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:Rahasia88oke@db-postgres-1:5432/postgres?sslmode=disable
    links:
      - db-postgres-1
    depends_on:
      - db-postgres-1

networks:
  default:
    external: true
    name: prometheus-metrics 